# config.yaml
# Existing simplified EMA strategy config retained for compatibility.

# API Configuration
api:
  account_name: 'Wood'
  testnet: false

# Existing EMA strategy block (unchanged)
strategy:
  symbol: 'ZBTUSDT'
  category: 'spot'
  timeframe: '5'
  ema_fast_period: 9
  ema_slow_period: 21
  trend_threshold_pct: 0.10
  entry_offset_pct: -0.1
  order_update_threshold_pct: 0.25
  max_allocation_usdt: 5000
  ema_allocations:
    ema9_pct: 25
    ema21_pct: 75
  take_profit_levels:
    tp1:
      pct: 0.5
      exit_pct: 10
    tp2:
      pct: 1.0
      exit_pct: 5
    tp3:
      pct: 2.5
      exit_pct: 10
  tp_execution_method: "limit"
  stop_loss_pct: 0.5
  hard_stop_loss_pct: 2.5
  entry_cooldown_seconds: 10

# Spot Rebalancer Configuration
rebalancer:
  # Target delta (total exposure in USDT)
  target_delta_usdt: 1000
  
  # Rebalance when divergence exceeds this amount
  rebalance_threshold_usdt: 250
  
  # Trend awareness (adjusts threshold based on trend)
  use_trend: true
  ema_fast_period: 9
  ema_slow_period: 21
  trend_threshold_pct: 0.1
  trend_multiplier: 1.5      # Be 1.5x more tolerant when trend supports position
  timeframe: '5'             # Candle interval for EMAs (minutes)
  
  # EMA-based opportunistic rebalancing (defensive strategy)
  ema_rebalance:
    enabled: true
    # Long in uptrend: take profits when price breaks X% above fast EMA
    uptrend_breakout_pct: 1.0           # 1% above EMA9 triggers defensive profit-taking
    # Long in downtrend: exit when price rallies back to fast EMA
    downtrend_ema_touch_pct: 0.2        # Within 0.2% of EMA9 triggers defensive exit
    # Minimum position size to trigger EMA-based rebalancing
    min_position_usdt: 100.0            # Only rebalance if position >= $100
    # Portion of position to reduce when EMA trigger hits
    ema_partial_ratio: 0.3              # Reduce 30% of position
    # Cooldown between EMA-triggered rebalances
    cooldown_seconds: 60                # Minimum 60 seconds between EMA rebalances
  
  # Order execution
  use_limit_orders: true     # Try limit orders first, then market if needed
  max_wait_seconds: 30       # Max time to wait for limit order before using market
  cooldown_seconds: 10       # Wait time between rebalance attempts

# Delta Management (legacy EMA runner)
delta_management:
  desired_delta_usdt: 1000
  divergence_threshold_usdt: 500
  divergence_timeout_seconds: 360

# Runtime Settings (shared)
runtime:
  duration_seconds: 86400
  status_interval: 60
  exit_on_shutdown: false
  pause_mode: false
