# config_simple.yaml
# Simplified EMA Strategy Configuration

# API Configuration
api:
  # Account name - this will be used to construct environment variable names
  # For example: "Wood" -> BYBIT_API_KEY_Wood, BYBIT_API_SECRET_Wood
  account_name: 'Wood'  # Options: 'Wood', 'Hyma', or any other account name
  testnet: false  # Set to false for live trading
  
strategy:
  # Trading pair
  symbol: 'XPLUSDT'
  category: 'linear'  # 'linear' for perpetuals, 'spot' for spot
  
  # Timeframe (candle interval for EMA calculations)
  timeframe: '5'  # 1, 3, 5, 15, 30, 60, 120, 240, 360, 720, D, W, M
  
  # EMA Setti=gs
  ema_fast_period: 9
  ema_slow_period: 21
  trend_threshold_pct: 0.10          # Threshold for trend detection (0.1 = 0.1%)
  
  # Order Offset Settings
  entry_offset_pct: -0.1             # Offset for entry orders (0.5 = 0.5%)
  order_update_threshold_pct: 0.25   # Only update orders when price drifts this far from EMA (0.5 = 0.5%)
  
  # Position Sizing (in USDT)
  max_allocation_usdt: 5000        # Maximum total position (increased to handle current overrun)
  ema_allocations:
    ema9_pct: 25                   # 50% of max allocation for EMA9 entries
    ema21_pct: 75                  # 50% of max allocation for EMA21 entries
  
  # Risk Management - Multiple Take Profit Levels
  take_profit_levels:
    tp1:
      pct: 0.5                    # First TP at 0.5%
      exit_pct: 10                # Exit 20% of position
    tp2:
      pct: 1.0                    # Second TP at 1.0%
      exit_pct: 5                # Exit 10% of remaining position
    tp3:
      pct: 2.5                    # Third TP at 2.5%
      exit_pct: 10                # Exit 20% of remaining position (leave 50%)
  
  # Take Profit Execution Method
  tp_execution_method: "limit"    # "limit" for limit orders (visible on exchange), "market" for market execution
  
  # Stop Loss - Two-tier system
  stop_loss_pct: 0.5             # Conditional stop loss at 0.25% below/above slow EMA (EMA21) - only on candle close
  hard_stop_loss_pct: 2.5         # Hard stop loss at 1% below/above slow EMA (EMA21) - immediate trigger
  
  # Timing
  entry_cooldown_seconds: 10      # Wait 10 seconds between entries

# Delta Management Settings
delta_management:
  desired_delta_usdt: 0           # Target delta position (0 = neutral, +ve = long bias, -ve = short bias)
  divergence_threshold_usdt: 10000 # Allow this much divergence from desired delta before rebalancing
  divergence_timeout_seconds: 360 # Allow divergence for this many seconds before forcing rebalance
  
# Runtime Settings
runtime:
  duration_seconds: 86400         # Run for 24 hours (or null for infinite)
  status_interval: 60             # Print status every 30 seconds
  exit_on_shutdown: false          # Set to false to hold positions when killed
  pause_mode: false               # Set to true to start in pause mode (no new trades)
